/*
 * File: app/view/Mainview.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScoreXpress.view.Mainview', {
    extend: 'Ext.Container',
    alias: 'widget.Mainview',

    requires: [
        'ScoreXpress.view.scoreList',
        'ScoreXpress.view.ScoreXpressForm',
        'Ext.TitleBar',
        'Ext.XTemplate',
        'Ext.tab.Panel',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.form.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                tpl: [
                    '<img width = 80 height= 80  align="left" src="resources/img/lowdown.png">'
                ],
                title: '<img height=35px width=35px  src="resources/img/cloudcircle.png" /><font size="4" color="white">ScoreXpress</font>'
            },
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'List',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'toolbar',
                                docked: 'bottom',
                                html: '',
                                title: '<font size="1" color="white">&#0169; 2014 Acentia All Rights Reserved.</font>',
                                items: [
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'button',
                                        id: 'addBtn',
                                        itemId: 'mybutton3',
                                        text: 'Add'
                                    }
                                ]
                            },
                            {
                                xtype: 'scorelist'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Edit',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'scorexpressform'
                            }
                        ]
                    }
                ],
                tabBar: {
                    docked: 'top',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    }
                }
            }
        ]
    }

});