/*
 * File: app/view/ScoreXpressForm.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScoreXpress.view.ScoreXpressForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.scorexpressform',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Select',
        'Ext.field.Spinner',
        'Ext.field.Hidden',
        'Ext.field.TextArea',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer'
    ],

    config: {
        layout: 'fit',
        scrollable: false,
        items: [
            {
                xtype: 'fieldset',
                scrollable: true,
                title: 'KPI Info',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'KPIName',
                        label: 'Name',
                        name: 'KPIName'
                    },
                    {
                        xtype: 'numberfield',
                        id: 'CurrentValue',
                        label: 'Current Value',
                        name: 'CurrentValue'
                    },
                    {
                        xtype: 'numberfield',
                        id: 'TargetValue',
                        label: 'Target Value',
                        name: 'TargetValue'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'LowIsBetter',
                        label: 'LowIsBetter',
                        name: 'LowIsBetter',
                        displayField: 'name',
                        store: 'LowIsBetterStore',
                        valueField: 'id'
                    },
                    {
                        xtype: 'spinnerfield',
                        id: 'MinTolerance',
                        label: 'MinTolerance',
                        name: 'MinTolerance',
                        maxValue: 100,
                        minValue: 0
                    },
                    {
                        xtype: 'spinnerfield',
                        id: 'MaxTolerance',
                        label: 'MinTolerance',
                        name: 'MaxTolerance',
                        maxValue: 100,
                        minValue: 0
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'Variance',
                        name: 'Variance'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'PercentChange',
                        name: 'PercentChange'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'LastUpdate',
                        name: 'LastUpdate'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'TimeSince',
                        name: 'TimeSince'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'ImageTag',
                        name: 'ImageTag'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'ArrowTag',
                        name: 'ArrowTag'
                    },
                    {
                        xtype: 'textareafield',
                        id: 'Comment',
                        label: 'Comment',
                        name: 'Comment'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        id: 'newBtn',
                        itemId: 'mybutton',
                        text: 'New'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'deleteBtn',
                        itemId: 'mybutton1',
                        text: 'Delete'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'saveBtn',
                        itemId: 'mybutton2',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});