/*
 * File: app/view/scoreList.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScoreXpress.view.scoreList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.scorelist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'scoreList',
        store: 'KPIStore',
        itemTpl: Ext.create('Ext.XTemplate', 
            '',
            '<div align=left><h1><strong><B><font size="4" color="black">{KPIName} </font></B></strong></h1></div></BR>',
            '<div><img align = left height=60px width=60px  src="resources/img/{ImageTag}.png" /></div>  ',
            '<div align=right><strong><B><font size="2" color="black">{LowIsBetter} </font></B></strong></div>',
            '           ',
            '<div><strong><B><font size="2" color="grey">Current: </font></B></strong><strong><B><font size="7" color="black">{CurrentValue}</font></B></strong></div>',
            '                <div align=right><strong><B><font size="2" color="grey">Target: </font></B></strong><strong><B><font size="5" color="black">{TargetValue}</font></B></strong></div>',
            '              ',
            '                <div><strong><B><font size="2" color="grey">Variance: </font></B></strong><strong><B><font size="5" color="black">{Variance}</font></B></strong></div>',
            '                <div><strong><B><font size="2" color="grey">Change: </font></B></strong><strong><B><font size="5" color="black">{PercentChange}%</font></B></strong> <img height=40px width=40px  src="resources/img/{ArrowTag}.png" /></div>',
            '                 <div><strong><B><font size="2" color="grey">Tolerance Min: -</font></B></strong><strong><B><font size="2" color="black">{MinTolerance}% </font></B></strong>',
            '                <strong><B><font size="2" color="grey"> Max: </font></B></strong><strong><B><font size="2" color="black">{MaxTolerance}%</font></B></strong></div>',
            '        ',
            '',
            '<!--     ',
            '	<div class="mod-content">',
            '	<h4><strong><B><font size="3" color="black">{KPIName} </font></B></strong></h4>',
            '	<p>',
            '	<img align = right height=60px width=60px  src="resources/img/{ImageTag}.png" />',
            '	<strong><B><font size="2" color="black">{LowIsBetter} </font></B></strong>',
            '	</p>',
            '	<table>',
            '	<thead>',
            '	<tr>',
            '	',
            '	</tr>',
            '	</thead>',
            '	<tbody>',
            '	<tr class="last">',
            '	<td><strong><B><font size="2" color="grey">Current: </font></B></strong></td>',
            '	<td><strong><B><font size="6" color="black">{CurrentValue}</font></B></strong></td>',
            '	</tr>',
            '	<tr class="last">',
            '	<td><strong><B><font size="2" color="grey">Target: </font></B></strong></td>',
            '	<td><strong><B><font size="5" color="black">{TargetValue}</font></B></strong></td>',
            '	</tr>',
            '	<tr class="last">',
            '	<td><strong><B><font size="2" color="grey">Variance: </font></B></strong></td>',
            '	<td><strong><B><font size="5" color="black">{Variance}</font></B></strong></td>',
            '	</tr>',
            '	<tr class="last">',
            '	<td><strong><B><font size="2" color="grey">Change: </font></B></strong></td>',
            '	<td><strong><B><font size="5" color="black">{PercentChange}%</font></B></strong> <img height=60px width=60px  src="resources/img/{ArrowTag}.png" /></td>',
            '	</tr>',
            '    ',
            '        <tr class="last">',
            '            <div align=left>',
            '	<td><strong><B><font size="1" color="grey">Tolerance: </font></B></strong></td>',
            '                <td><strong><B><font size="2" color="black">-{MinTolerance} / {MaxTolerance} <strong><B><font size="1" color="grey">Min/Max </font></B></strong></font></B></strong> </td>',
            '            </div>',
            '            </tr>',
            '        ',
            '      ',
            '	</tbody>',
            '	</table></div>',
            '-->',
            '',
            '',
            '',
            '',
            '<!--',
            '<div>',
            '    <table>',
            '        <tr>',
            '            <td><div  align=left><img height=80px width=80px  src="resources/img/{ImageTag}.png" /></div></td>',
            '            <div align=right><strong><B><font size="2" color="black">{LowIsBetter} </font></B></strong></div>',
            '            <td>',
            '                <div align=left><h2><strong><B><font size="3" color="black">{KPIName} </font></B></strong></h2></div>',
            '                 <div><strong><B><font size="2" color="grey">Current: </font></B></strong><strong><B><font size="7" color="black">{CurrentValue}</font></B></strong></div>',
            '                <div align=right><strong><B><font size="2" color="grey">Target: </font></B></strong><strong><B><font size="5" color="black">{TargetValue}</font></B></strong></div>',
            '              ',
            '                <div><strong><B><font size="2" color="grey">Variance: </font></B></strong><strong><B><font size="5" color="black">{Variance}</font></B></strong></div>',
            '                <div><strong><B><font size="2" color="grey">Change: </font></B></strong><strong><B><font size="5" color="black">{PercentChange}%</font></B></strong> <img height=40px width=40px  src="resources/img/{ArrowTag}.png" /></div>',
            '                 <div><strong><B><font size="2" color="grey">Tolerance Min: -</font></B></strong><strong><B><font size="2" color="black">{MinTolerance}% </font></B></strong>',
            '                <strong><B><font size="2" color="grey"> Max: </font></B></strong><strong><B><font size="2" color="black">{MaxTolerance}%</font></B></strong></div>',
            '            </td>',
            '        </tr>',
            '    </table>',
            '</div>',
            '-->',
            '<!--',
            '			<div  >',
            '		        <ul>',
            '		        	<li>',
            '                        <p>',
            '                       ',
            '                            <img width = 80 height= 80  align="left" src="resources/img/{ImageTag}.png">',
            '		            	<h2><strong><B><font size="3" color="black">{KPIName} </font></B></strong></h2>',
            '                            <div align=right><strong><B><font size="3" color="black">{LowIsBetter} </font></B></strong></div>',
            '                        <p>{TimeSince)}</p></br>',
            '		               <strong><B><font size="5" color="black">{Variance}</font></B></strong></br>',
            '                       <strong><B><font size="5" color="black">{PercentChange}%</font></B></strong></br>',
            '',
            '                    <div><strong><B><font size="2" color="black">Tolerance Min: -{MinTolerance}% </font></B></strong>',
            '                    <B><font size="2" color="black"> Max: {MaxTolerance}%</font></B></strong></div></br>',
            '                       <div align=right>',
            '                        <strong><B><font size="7" color="black">{CurrentValue}</font></B></strong></br>',
            '                       <strong><B><font size="5" color="black">{TargetValue}</font></B></strong></br></p>',
            '                        </div>',
            '		               </br>',
            '',
            '                     </li>',
            '		        </ul>',
            '			</div>',
            '-->',
            '',
            '		                                      ',
            '  <!--                  ',
            '  <div>',
            '    <div> <strong><B><font size="6" color="white">{CurrentValue}</font></B></strong><strong><font size="2" color="white"></font></strong>',
            '           </div></br>',
            '     <div><strong><B><font size="6" color="white"> {TargetValue}</font></B></strong> <font size="2" color="white"></font></strong></div></br>',
            '      <div> <strong><B><font size="6" color="white"> {Variance}</font></B></strong><strong><font size="2" color="white"></font></strong></div>',
            '      <div><strong><B><font size="2" color="white">Tolerance Min: -{MinTolerance}% </font></B></strong>',
            '                <B><font size="2" color="white"> Max: {MaxTolerance}%</font></B></strong></div>',
            '</div>',
            '',
            '		        </ul>',
            '			</div>',
            '',
            '-->',
            '',
            {
                isLargeCity: function(values) {
                    //alert(values);

                }
            }
        )
    }

});