/*
 * File: app/model/KPIModel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ScoreXpress.model.KPIModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.LocalStorage',
        'Ext.data.Field'
    ],

    config: {
        proxy: {
            type: 'localstorage',
            id: 'Kpi-Trk'
        },
        fields: [
            {
                name: 'KPIName'
            },
            {
                name: 'CurrentValue'
            },
            {
                name: 'TargetValue'
            },
            {
                name: 'MinTolerance'
            },
            {
                name: 'MaxTolerance'
            },
            {
                name: 'Variance',
                type: 'float'
            },
            {
                name: 'PercentChange',
                type: 'float'
            },
            {
                name: 'LowIsBetter',
                type: 'string'
            },
            {
                name: 'Comment'
            },
            {
                dateFormat: 'Y.m.d',
                defaultValue: 'new Date()',
                name: 'LastUpdate',
                type: 'date'
            },
            {
                dateFormat: '',
                name: 'TimeSince',
                type: 'date'
            },
            {
                name: 'ImageTag'
            },
            {
                name: 'ArrowTag'
            }
        ]
    }
});